// <auto-generated />
namespace Icogram.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Ban34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ban34));
        
        string IMigrationMetadata.Id
        {
            get { return "201710291959294_Ban34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
