// <auto-generated />
namespace Icogram.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CommandDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommandDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201711021739304_Command Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
