// <auto-generated />
namespace Icogram.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class deletedallmessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedallmessages));
        
        string IMigrationMetadata.Id
        {
            get { return "201802051712213_deleted all messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
